### PR TITLE
Feature/moments

### PR DESCRIPTION
**Pull request by meganmcquillan**
Hi DragonCherry!

Here's the PR with the right branch. I also made the change so that Moments shows as the first album. Some issues/general comments:

1) We still need the localization strings for the new album.
2a) I didn't get the spacing right between sections 0 & 1, it would be great if you could help with that.
2b) Even with that fixed, it would probably still be good to make the Moments album stand out a little more. In the standard table view picker they have a bottom border on that section. What are your thoughts on doing the same?
3) It's currently crashing if you try to create a new album, so I think I introduced a bug there. I'll investigate, but if you spot the issue, please let me know.

Please try it out and let me know what issues you spot; it's far from perfect. Check out the code too :)

Thank you!

### CODE REVIEW

**Comment by DragonCherry** [comment]
OK, I can get into it from 29, Jan, since I’m on vacation in Italy. Thank yiu!

**Comment by meganmcquillan** [comment]
No problem, enjoy your vacation!

**Comment by meganmcquillan** [comment]
Hi DragonCherry! Do you think you'll have a chance to look at this sometime soon? Thanks!

**Comment by DragonCherry** [comment]
Sorry for my late reply. It's a little bit hard to spare time these days. I'm on the way from today!

**Pull request merged**
